package com.metanet.login.global.config;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.Operation;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.media.StringSchema;
import io.swagger.v3.oas.models.parameters.Parameter;
import io.swagger.v3.oas.models.responses.ApiResponse;
import io.swagger.v3.oas.models.responses.ApiResponses;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;
import io.swagger.v3.oas.models.tags.Tag;
import java.util.List;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class OpenApiConfig {
	private static final String BEARER_AUTH = "bearerAuth";

	@Bean
	OpenAPI openAPI() {
		return new OpenAPI()
				.info(new Info()
						.title("Spring Auth Template API")
						.version("v1")
						.description("JWT authentication, Google OAuth2 login, and user account API"))
				.addTagsItem(new Tag()
						.name("OAuth2")
						.description("Google OAuth2 browser redirect flow"))
				.components(new Components()
						.addSecuritySchemes(BEARER_AUTH, new SecurityScheme()
								.type(SecurityScheme.Type.HTTP)
								.scheme("bearer")
								.bearerFormat("JWT")))
				.path("/oauth2/authorization/google", new io.swagger.v3.oas.models.PathItem()
						.get(new Operation()
								.addTagsItem("OAuth2")
								.summary("Start Google OAuth2 login")
								.description("""
										Redirects the browser to Google's authorization page.
										Call this URL from a browser or frontend login button, not from an AJAX request.
										""")
								.security(List.of())
								.responses(new ApiResponses()
										.addApiResponse("302", new ApiResponse()
												.description("Redirect to Google authorization endpoint")))))
				.path("/login/oauth2/code/google", new io.swagger.v3.oas.models.PathItem()
						.get(new Operation()
								.addTagsItem("OAuth2")
								.summary("Google OAuth2 callback")
								.description("""
										Callback URL handled by Spring Security after Google login.
										Register this exact URL as an Authorized redirect URI in Google Cloud Console.
										On success, the backend redirects to the configured frontend success URL with a one-time code.
										""")
								.addParametersItem(new Parameter()
										.name("code")
										.in("query")
										.required(true)
										.schema(new StringSchema())
										.description("Authorization code sent by Google"))
								.addParametersItem(new Parameter()
										.name("state")
										.in("query")
										.required(true)
										.schema(new StringSchema())
										.description("OAuth2 state value generated by Spring Security"))
								.security(List.of())
								.responses(new ApiResponses()
										.addApiResponse("302", new ApiResponse()
												.description("Redirect to frontend success or failure URL")))))
				.addSecurityItem(new SecurityRequirement().addList(BEARER_AUTH));
	}
}
